const locator = require('../../pageobject/pageElements/Locator.json')

export class homePageElements{
    menu_button(){
        cy.get(locator.HomePage.menu_button).click()
    }
    verify_menuButton(){
        cy.get(locator.HomePage.inventory_menu).should('be.visible')
        cy.get(locator.HomePage.about_menu).should('be.visible')
        cy.get(locator.HomePage.logout_menu).should('be.visible')
        cy.get(locator.HomePage.resetAppState_menu).should('be.visible')
    }
    chart_button(){
        cy.get(locator.HomePage.chart_button).click()
        cy.get(locator.ChartPage.checkout_button).should('be.visible')

    }
    verify_homePageCopy(){
        cy.get(locator.HomePage.chart_button).should('be.visible')
        cy.get(locator.HomePage.page_title).should('be.visible')
        cy.get(locator.HomePage.product_sort).should('be.visible')
        cy.get(locator.HomePage.list_product).should('be.visible')
        cy.get(locator.HomePage.productPrice_label).should('be.visible')
        cy.get(locator.HomePage.product_title).should('be.visible')
        cy.get(locator.HomePage.productDescription).should('be.visible')
        cy.get(locator.HomePage.footer).scrollIntoView()        
    }
    addProductToChart(){
        cy.get(locator.HomePage.addToChart_button1).click()
        cy.get(locator.HomePage.addToChart_button2).click()
    }
    verifyChartData(){
        cy.get(locator.ChartPage.firstItem).should('be.visible')
    }
    removeItemFromChart(){
        cy.get(locator.ChartPage.remove_button1).click()
        cy.get(locator.ChartPage.remove_button2).click()
    }
    clickBtnContinueShopping(){
        cy.get(locator.ChartPage.btn_continue).click()
    }
    addAllProductToChart(){
        cy.get(locator.HomePage.addToChart_button1).click()
        cy.get(locator.HomePage.addToChart_button2).click()
        cy.get(locator.HomePage.addToChart_button3).click()
        cy.get(locator.HomePage.addToChart_button4).click()
        cy.get(locator.HomePage.addToChart_button5).click()
        cy.get(locator.HomePage.addToChart_button6).click()
    }
    removeAllProductFromChart(){
        cy.get(locator.ChartPage.remove_button1).click()
        cy.get(locator.ChartPage.remove_button2).click()
        cy.get(locator.ChartPage.remove_button3).click()
        cy.get(locator.ChartPage.remove_button4).click()
        cy.get(locator.ChartPage.remove_button5).click()
        cy.get(locator.ChartPage.remove_button6).click()
    }
    verifyIconCounter(){
        cy.get(locator.ChartPage.icon_count).should('not.exist')
    }

}